services:
  - type: web
    name: country-game
    env: static
    buildCommand: npm install && npm run build-only
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 22
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
